# Generated by Django 4.2.8 on 2024-02-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_is_paid_alter_balance_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
